export const Types = {
  INIT: '@@init',
  SEARCH_FILES: 'SEARCH_FILES',
  SEARCH_QUERY: 'SEARCH_QUERY',
  SAVE_FILES: 'SAVE_FILES',
  FETCH_FILES_FAILURE: 'FETCH_FILES_FAILURE',
  FETCH_FILES_SUCCESS: 'FETCH_FILES_SUCCESS',
};
